[build]
  publish = "."

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/app.js"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/style.css"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/about.html"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

